- backend/src/main/java/com/example/model/Cpu.java
- backend/src/main/java/com/example/model/Gpu.java
- backend/src/main/java/com/example/model/Os.java
- backend/src/main/java/com/example/model/Pc.java
- backend/src/main/java/com/example/repository/BookRepository.java
- backend/src/main/java/com/example/repository/CPURepository.java
- backend/src/main/java/com/example/repository/CartProductRepository.java
- backend/src/main/java/com/example/repository/CpuRepository.java
- backend/src/main/java/com/example/repository/GPURepository.java
- backend/src/main/java/com/example/repository/GpuRepository.java
- backend/src/main/java/com/example/repository/LanguageRepository.java
- backend/src/main/java/com/example/repository/OSRepository.java
- backend/src/main/java/com/example/repository/OrderProductRepository.java
- backend/src/main/java/com/example/repository/OsRepository.java
- backend/src/main/java/com/example/repository/PCRepository.java
- backend/src/main/java/com/example/repository/PcRepository.java
- backend/src/main/java/com/example/repository/PurposeRepository.java
- backend/src/main/java/com/example/repository/ReviewRepository.java
- backend/src/main/java/com/example/repository/UserRepository.java
> chore: javadoc, file nameを変更

- frontend/src/features/order/OrderPage.tsx
- frontend/src/features/order/schema/orderSchema.ts
close #8 
- 注文時に届け先の住所を変更可能に
-
> feat: 注文時に宛先を変更可能に

- backend/src/main/java/com/example/controller/PCController.java
- backend/src/main/java/com/example/service/PCService.java
- PCの詳細情報を取得する機能を実装
- エンドポイントにpcIDを指定することで取得可能
-
> PCの詳細情報を取得する機能の実装

- backend/src/main/java/com/example/controller/BookController.java
- backend/src/main/java/com/example/controller/PcController.java
- backend/src/main/java/com/example/dto/request/AddBookRequest.java
- backend/src/main/java/com/example/service/BookService.java
- backend/src/main/java/com/example/service/PcService.java
- 本の登録機能を実装
- PCコントローラーおよびPCサービスのリファクタ
- 追加機能はPCのときと一緒です
> 本の登録機能の実装およびリファクタリング

- README.md
- backend/document/sql/insert-cart-products.sql
- backend/src/main/java/com/example/controller/OrderController.java
- backend/src/main/java/com/example/repository/BookRepository.java
- backend/src/main/java/com/example/service/BookService.java
- backend/src/main/java/com/example/service/OrderProductService.java
- package-lock.json
#57 
- lintエラーの解消
- カート用のinsert文を追加
-
> chore: cart用のsqlを追加

- backend/src/main/java/com/example/controller/PcController.java
- backend/src/main/java/com/example/repository/PcRepository.java
- backend/src/main/java/com/example/service/PcService.java
> PurposeのIDを基に一致するPC一覧を取得する機能の実装

- backend/src/main/java/com/example/controller/PcController.java
- backend/src/main/java/com/example/repository/PcRepository.java
- backend/src/main/java/com/example/service/PcService.java
- GPUのIDを基に一致するPC一覧を取得する機能の実装
-
> GPUのIDを基に一致するPC一覧を取得する機能の実装

- backend/src/main/java/com/example/controller/BookController.java
- backend/src/main/java/com/example/service/BookService.java
- 書籍に定義することが可能な言語一覧を取得する機能の実装
- メモ：書籍登録機能かユーザ登録でアンケート部分を設ける場合、興味がある言語について選択する機能で使えると思う（別に使わなくても可）
- PCのOSやCPUなどの一覧取得は一旦今出してるプルリクが全部通ったら追加する予定
> 書籍に定義可能な言語の一覧取得機能の実装

- backend/src/main/java/com/example/config/GlobalExceptionHandler.java
- backend/src/main/java/com/example/controller/OrderController.java
- backend/src/main/java/com/example/controller/ProductController.java
- backend/src/main/java/com/example/dto/response/OrderHistoryResponse.java
- backend/src/main/java/com/example/dto/response/OrderProductResponse.java
- backend/src/main/java/com/example/model/Order.java
- backend/src/main/java/com/example/repository/OrderRepository.java
- backend/src/main/java/com/example/service/OrderService.java
- frontend/src/features/order/OrderHistory.tsx
- 注文履歴を取得する/orders/historyというエンドポイントを追加
- 注文履歴をフロント画面で表示させる
-
> feat: 注文履歴を取得するバックエンドを実装

- backend/.env.example
- backend/.gitignore
- backend/build.gradle
- backend/docker-compose.yml
- backend/src/main/java/com/example/config/GlobalExceptionHandler.java
- backend/src/main/java/com/example/controller/OrderController.java
- backend/src/main/java/com/example/service/MailService.java
- backend/src/main/resources/application.yml
#32 
- 注文完了時に注文完了メールを送信するように
- envファイルないと動かなくなるので設定が必要
> feat: 注文完了メール送信機能を実装

- backend/src/main/java/com/example/controller/BookController.java
- backend/src/main/java/com/example/controller/PcController.java
- backend/src/main/java/com/example/repository/BookRepository.java
- backend/src/main/java/com/example/repository/PcRepository.java
- backend/src/main/java/com/example/service/BookService.java
- backend/src/main/java/com/example/service/PcService.java
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/ui/command.tsx
- frontend/src/components/ui/dialog.tsx
- frontend/src/features/product/ProductPage.tsx
- frontend/src/features/product/components/ProductList.tsx
- frontend/src/features/product/components/SearchForm.tsx
#73 
- 曖昧検索機能を実装
- オートコンプリート機能を実装（パフォーマンス対策済み）
-
> feat: 曖昧検索機能を実装

- backend/src/main/java/com/example/controller/BookController.java
> コンフリ解消の時に間違えて消したimportの上げ直し

- frontend/src/features/user/UserLoginPage.tsx
- frontend/src/features/user/UserRegisterPage.tsx
#129 
close #129 
- ログイン画面、新規登録画面に商品一覧画面への導線を追加
Snipping Toolはいっちゃったごめん
-
> ログイン画面新規登録画面に商品一覧画面への導線を追加

- frontend/src/features/product/ProductPage.tsx
- frontend/src/features/product/components/ProductCard.tsx
- frontend/src/features/product/components/Sidebar.tsx
- frontend/src/features/product/hooks/useProductData.ts
- frontend/src/features/product/hooks/useProductFilters.ts
- frontend/src/features/product/types/Product.ts
> サイドバーの不具合の修正

- backend/src/main/java/com/example/controller/UserController.java
- frontend/package-lock.json
- frontend/src/components/password-input.tsx
- frontend/src/features/order/OrderPage.tsx
- frontend/src/features/user/UserLoginPage.tsx
- frontend/src/features/user/UserRegisterPage.tsx
- frontend/src/features/user/schema/registerFormSchema.ts
ユーザー登録画面、ログイン画面の
- パスワードをボタンで見える、隠す
- パスワードバリデーションの堅牢化、電話番号のバリデーションを具体化
- フォーム送信時ではなく、onBlurでリアルタイムバリデーションに変更
- 郵便番号、電話番号等の例をplaceholderで提示
-
> パスワード堅牢化、見える化。ログイン画面と登録画面修正

- backend/src/main/java/com/example/controller/UserController.java
- frontend/src/features/order/OrderPage.tsx
- frontend/src/features/order/schema/orderSchema.ts
- frontend/src/features/user/UserLoginPage.tsx
- 注文確認ページとユーザー登録画面のバリデーション、placeholder、ラベル名の統一
- Fix: 注文確認ページの支払い方法のバリデーション修正
-
> ログの削除、注文確認ページとユーザー登録画面のバリデーションを合わせた

- backend/src/main/java/com/example/controller/UserController.java
- backend/src/main/java/com/example/service/UserService.java
- backend/src/main/java/com/example/validation/UniqueEmailValidator.java
- frontend/package-lock.json
- frontend/src/features/user/UserRegisterPage.tsx
- ユーザー登録時メール重複チェックで、ユーザーが見つからない場合に例外を発生させてたので、例外を発生させないようにした
-
> ユーザー登録時メールアドレスチェックのロジック変更、ログイン画面のimport修正

- frontend/src/features/order/OrderPage.tsx
- frontend/src/features/user/UserLoginPage.tsx
- frontend/src/features/user/UserRegisterPage.tsx
- formのvalidationをonChangeに
- ログイン後の遷移を適切な部分になげる
- 注文確定ボタンをクリックできるように
-
> fix: フロントのバグを修正

- frontend/src/features/user/UserLoginPage.tsx
- frontend/src/features/user/UserRegisterPage.tsx
- frontend/src/features/user/components/UserHeader.tsx
> fix: 商品一覧へのページ遷移を修正

- frontend/src/features/product/book/BookDetail.tsx
- frontend/src/features/product/components/RecommendedByContentBaseProducts.tsx
- frontend/src/features/product/components/ReviewInfo.tsx
- frontend/src/features/product/pc/PcDetail.tsx
> style:　スタイル修正

- frontend/src/components/layout/Header.tsx
> fix: ログアウト時に明示的にuserを削除
